"""Added Devices Table

Revision ID: 1a5eebae883b
Revises: 82e2afeb520c
Create Date: 2018-01-12 02:52:18.821887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5eebae883b'
down_revision = '82e2afeb520c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('devId', sa.String(length=5), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['instructor.id'], ),
    sa.PrimaryKeyConstraint('devId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
