"""Instructor table

Revision ID: 23826a457a28
Revises: 
Create Date: 2018-01-12 01:21:26.032821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23826a457a28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=10), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Student')
    op.drop_table('Attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attendance',
    sa.Column('sID', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('FirstName', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Day1', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('Day2', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('Day3', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('Day4', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('Day5', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('Day6', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('Day7', mysql.VARCHAR(length=2), nullable=True),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_table('Student',
    sa.Column('FirstName', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sID', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('fID', mysql.VARCHAR(length=10), nullable=True),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('instructor')
    # ### end Alembic commands ###
