"""Added tables Classes, and Attendance

Revision ID: 8d1f66661c65
Revises: 1a5eebae883b
Create Date: 2018-01-15 01:10:13.622417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1f66661c65'
down_revision = '1a5eebae883b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('classId', sa.String(length=10), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('TAs', sa.String(length=50), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['instructor.id'], ),
    sa.PrimaryKeyConstraint('classId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    # ### end Alembic commands ###
