"""Added Semesters

Revision ID: bc489aa95fe6
Revises: 8d1f66661c65
Create Date: 2018-01-15 02:44:07.345580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc489aa95fe6'
down_revision = '8d1f66661c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('sem', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('sem')
    )
    op.add_column(u'classes', sa.Column('sem', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'classes', 'sem')
    op.drop_table('semesters')
    # ### end Alembic commands ###
