"""Updated Instructor Table

Revision ID: cd045283930b
Revises: 23826a457a28
Create Date: 2018-01-12 01:37:47.036366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd045283930b'
down_revision = '23826a457a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor', sa.Column('test', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructor', 'test')
    # ### end Alembic commands ###
