"""Fixed attribute lengths

Revision ID: e2d4b4c1bd14
Revises: bc489aa95fe6
Create Date: 2018-01-15 02:54:19.469448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d4b4c1bd14'
down_revision = 'bc489aa95fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('sem', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('sem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semesters')
    # ### end Alembic commands ###
